{{- if .Values.init.enabled}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: setup-ceph-fs-dirs
          image: "{{ .Values.init.image}}"
          command:
            - sh
            - -c
            - |
              echo "Running Kafka connect script : {{ .Values.init.script}}"
                chmod +x {{ .Values.init.script}} && . {{ .Values.init.script}}
                echo "Completed running Kafka connect script"
          volumeMounts:
            - mountPath: /opt/ceph
              name:  data
      restartPolicy: Never
      volumes:
        - name: data
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: {{.Values.persistence.cephFs.fsName}} # name of the filesystem specified in the filesystem CRD.
              clusterNamespace: {{.Values.persistence.cephFs.clusterNamespace}} # namespace where the Rook cluster is deployed
              # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
              # the path must exist on the filesystem, otherwise mounting the filesystem at that path will fail
              # path: /path/to/existing/dir
  backoffLimit: 0
{{- end}}