{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: connect-pv
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  accessModes:
  - ReadWriteOnce
{{- end}}
{{- end}}
