{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.storageClass }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.name }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  accessModes:
  - ReadWriteOnce
{{- end}}
{{- end}}
